"""
Django settings for gestor_eventos project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import inspect 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--ndwgfhsgc0f6-z*21*dx)ft@1tc9e#u(spqkw6(nys5jw2gni'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'eventos',
    'rest_framework.authtoken',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestor_eventos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestor_eventos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
 'DEFAULT_AUTHENTICATION_CLASSES': [
 'rest_framework.authentication.TokenAuthentication',
 'rest_framework.authentication.SessionAuthentication',
 ],
 'DEFAULT_PERMISSION_CLASSES': [
 'rest_framework.permissions.IsAuthenticatedOrReadOnly',
 ],
 'DEFAULT_FILTER_BACKENDS': [
 'django_filters.rest_framework.DjangoFilterBackend',

 ],
 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', 
}

SPECTACULAR_SETTINGS = {
'TITLE': 'gestor_eventos',
'DESCRIPTION': inspect.cleandoc("""
## Bem-vindo à gestor_eventos!  
                             
 ### Eventos
- **Listar eventos** (`GET /api/eventos/`) sem autenticação
- **Criar eventos** (`POST /api/eventos/`) com autenticação
- **Atualizar eventos** (`PUT/PATCH /api/eventos/{id}/`) com autenticação
- **Excluir eventos** (`DELETE /api/eventos/{id}/`) com autenticação
        
### Participantes
- **Listar participantes** (`GET /api/participantes/`) sem autenticação
- **Criar participantes** (`POST /api/participantes/`) com autenticação
- **Atualizar participantes** (`PUT/PATCH /api/participantes/{id}/`) com autenticação
- **Excluir participantes** (`DELETE /api/participantes/{id}/`) com autenticação
                                 
 ### Atividades
- **Listar atividades** (`GET /api/atividades/`) sem autenticação
- **Criar atividades** (`POST /api/atividades/`) com autenticação
- **Atualizar atividades** (`PUT/PATCH /api/atividades/{id}/`) com autenticação
- **Excluir atividades** (`DELETE /api/atividades/{id}/`) com autenticação

                         
 ### Autenticação
 Use o endpoint `/api/token/` para obter seu token e inclua no cabeçalho:

 Authorization: Token <sua_chave>
 ```
 """),
 'VERSION': '1.0.0',
 'SERVE_INCLUDE_SCHEMA': False,
 'SECURITY': [{'TokenAuth': []}],
 'COMPONENTS': {
 'securitySchemes': {
 'TokenAuth': {
 'type': 'apiKey',
 'in': 'header',
 'name': 'Authorization',
 'description': 'Use o formato: Token <sua_chave>',
 },
 },
 },
}